layout_spectrum: 0.5698925
color:
  saturation: 0.6457754
  lightness: 0.3584229
  brandStrength: 0.9444444
  brandColors:
    - '#01090C'
    - '#1B2429'
    - '#414B4D'
    - '#C0AEAA'
    - '#81817F'
  rhythmicContrast: 0.7485409
typography_spectrum: 0.4516129
name: Remo Fritzsche
